path:
  data_path: "resources/data"
  checkpoint_path: "resources/ckpt"
  log_path: "log"
  heatmap_path: "heatmap"

human:
  shape: [ 200, 200, 3 ]
  min_age: 1
  max_age: 90

nnet:
  epochs: 50
  batch_size: 256
  usage_rate: 1.0
  validation_split_rate: 0.1
  normalize: true
  freeze: true
  weights_filename: "final.h5"
  checkpoint_filename: "{epoch}.h5"

logging:
  train_filename: "{timestamp}.csv"
  dataset_loader_filename: "dataset_loader.json"